trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  tag: $(Build.BuildId)
  acrName: demoacr839
  aksResourceGroup: demo-aks-rg
  aksCluster: demo-aks
  namespace: default

stages:
  - stage: BuildPushImage
    displayName: Build & Push Docker Image
    jobs:
      - job: Build_Image
        displayName: Build & Push Docker Image
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ado_sc'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              docker build -t $(acrName).azurecr.io/app:$(tag) .
              az acr login -n $(acrName)
              docker push $(acrName).azurecr.io/app:$(tag)

  - stage: DeployToAKS
    displayName: Deploy to AKS
    jobs:
      - job: DeployToAKS
        displayName: Deploying to AKS
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ado_sc'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksCluster)
              sed 's/\${acrName}/$(acrName)/g' k8s/vote_deploy.yaml > k8s/vote_deploy_substituted.yaml
              sed 's/\${tag}/$(tag)/g' k8s/vote_deploy_substituted.yaml > k8s/vote_deploy_new_build.yaml
              kubectl apply -f k8s/vote_deploy_new_build.yaml --validate=false
